myList1=["Apple","Banana","Oranges"]
myList2=["Grapes"]
# x1=myList1.append(myList2)
# print(myList1)
# print(x1)
# x="Dates"
# myList1.append(x)
# print(myList1)
# myList1.clear()
# print(myList1)
# print(myList1.count("Banana"))
# z=myList1.copy()
# print(z)
# myList1.extend(myList2)
# print(myList1)
# myList1.insert(1,"Grapes")
# print(myList1)
myList=[2,7,8,5,6,23,56]
x=myList.pop(1)
print(x)
print(myList)
myList.remove(8)
print(myList)
myList.reverse()
print(myList)
myList.sort()
print(myList)
